[package]
name = "thalamus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
log = "0.4.14"
rouille = "3.6.2"
error-chain = "0.12.4"
simple_logger = { git = "https://github.com/PixelCoda/rust-simple_logger.git", version = "1.13.6" }
wav = "1.0.0"
hound = "3.4.0"
sudo = "0.5"
clearscreen = "2.0.1"