[package]
name = "Thalamus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
serde = { version = "1.0.133", features = ["derive"] }
log = "0.4.14"
whisper-rs = "0.7.0"
rouille = "3.6.2"
error-chain = "0.12.4"
opencl3 = "0.9.3"
tch = "0.10.1"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "json", "multipart"] }
simple_logger = { git = "https://github.com/PixelCoda/rust-simple_logger.git", version = "1.13.6" }
openssl = { version = "*", features = ["vendored"] }
trust-dns-resolver = "0.20.3"
titlecase = "2.2.1"
wav = "1.0.0"
hound = "3.4.0"
noise-gate = { git = "https://github.com/Michael-F-Bryan/noise-gate.git", version = "0.1.1-alpha.0" }
zip = "0.5.13"
shuteye = "0.3.3"
sudo = "0.5"

[features]
default = ["reqwest/default-tls", "trust-dns-resolver/dns-over-native-tls"]
vendored-openssl = ["openssl/vendored"]
rustls = ["reqwest/rustls-tls", "trust-dns-resolver/dns-over-rustls"]